#!/bin/sh

if which dirname 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: dirname: command not found" 1>&2
  exit 1
fi

if which pwd 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: pwd: command not found" 1>&2
  exit 1
fi

bindir=`(cd \`dirname "$0"\`; pwd)`
dir=`dirname "$bindir"`
libdir="${dir}/lib"

if which mktemp 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: mktemp: command not found" 1>&2
  exit 1
fi

if which "${bindir}/hack-gcc-specs" 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: ${bindir}/hack-gcc-specs: command not found" 1>&2
  exit 1
fi

if which "${bindir}/g++" 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: ${bindir}/g++: command not found" 1>&2
  exit 1
fi

if which rm 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: rm: command not found" 1>&2
  exit 1
fi

specs=`mktemp` || exit

PATH="$PATH${PATH:+:}$bindir"
export PATH

{ "${bindir}/hack-gcc-specs" > "$specs"; } && "${bindir}/g++" -specs="$specs" "$@"
result=$?

rm -f "$specs"

exit $result
