#!/usr/bin/env bash

dir="${0%/*}"
if [ "$dir" != "." ]; then
    dir="$(dirname "$0")"
    if [ "$dir" = "." ]; then
	echo "ERROR: this script should be called by the command containing the directory separator '/'." 1>&2
	exit 1
    fi
fi
dir="$(cd "$dir"; pwd)"
libdir="$(dirname "$dir")/lib"
bindir="$(dirname "$dir")/bin"

if uname | grep -Fq 'Linux'; then
    LD_LIBRARY_PATH="${libdir}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
    export LD_LIBRARY_PATH
    LD_RUN_PATH="${libdir}${LD_RUN_PATH:+:${LD_RUN_PATH}}"
    export LD_RUN_PATH
elif uname | grep -Fq 'CYGWIN'; then
    PATH="$bindir${PATH:+:${PATH}}"
    export PATH
else
    exit 1
fi

"${dir}/clang" "$@"
result=$?

exit $result
