#!/usr/bin/env bash

dir="${0%/*}"
if [ "$dir" != "." ]; then
    dir="$(dirname "$0")"
    if [ "$dir" = "." ]; then
	echo "ERROR: this script should be called by the command containing the directory separator '/'." 1>&2
	exit 1
    fi
fi
dir="$(cd "$dir"; pwd)"
libdir="$(dirname "$dir")/lib"
bindir="$(dirname "$dir")/bin"

if uname | grep -Fq 'Linux'; then
    env LD_RUN_PATH="${LD_RUN_PATH:+$LD_RUN_PATH:}$libdir" "${dir}/clang" "$@"
elif uname | grep -Fq 'CYGWIN'; then
    env PATH="${PATH:+$PATH:}$bindir" "${dir}/clang" "$@"
else
    exit 1
fi
result=$?

exit $result
