#!/usr/bin/env bash

dir="${0%/*}"
if [ "$dir" != "." ]; then
    dir="$(dirname "$0")"
    if [ "$dir" = "." ]; then
	echo "ERROR: this script should be called by the command containing '/'." 1>&2
	exit 1
    fi
fi
dir="$(cd "$dir"; pwd)"
prefix="$(cd "${dir}/.."; pwd)"

OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
LD_LIBRARY_PATH="${prefix}/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH

ulimit -S -t 60
"${dir}/clang++" "$@"
result=$?
ulimit -t unlimited

LD_LIBRARY_PATH="$OLD_LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
if [ ! -n "$LD_LIBRARY_PATH" ]; then
  unset LD_LIBRARY_PATH
fi
unset OLD_LD_LIBRARY_PATH

exit $result
