#!/usr/bin/env bash

dir="${0%/*}"
if [ "$dir" != "." ]; then
    dir="$(dirname "$0")"
    if [ "$dir" = "." ]; then
	echo "ERROR: this script should be called by the command containing the directory separator '/'." 1>&2
	exit 1
    fi
fi
dir="$(cd "$dir"; pwd)"
libdir="$(dirname "$dir")/lib"

if uname | grep -Fq 'Linux'; then
    # It is more suitable to set `LD_RUN_PATH' environment variable. However,
    # gold linker has a bug that ignores this environment variable.
    # http://sourceware.org/bugzilla/show_bug.cgi?id=13764
    "${dir}/g++" -Wl,-rpath="$libdir" "$@"
elif uname | grep -Fq 'CYGWIN'; then
    env PATH="${dir}/../bin${PATH:+:$PATH}" "${dir}/g++" "$@"
else
    exit 1
fi
result=$?

exit $result
