#!/usr/bin/env bash

dir="${0%/*}"
if [ "$dir" != "." ]; then
    dir="$(dirname "$0")"
    if [ "$dir" = "." ]; then
	echo "ERROR: this script should be called by the command containing the directory separator '/'." 1>&2
	exit 1
    fi
fi
dir="$(cd "$dir"; pwd)"

/usr/bin/env LD_LIBRARY_PATH=${dir}/../../lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} "${dir}/gcc" "$@"
result=$?

exit $result
