#!/bin/sh

if which dirname 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: dirname: command not found" 1>&2
  exit 1
fi

if which pwd 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: pwd: command not found" 1>&2
  exit 1
fi

bindir=`(cd \`dirname "$0"\`; pwd)`
dir=`dirname "$bindir"`
libdir="${dir}/lib"

if which mktemp 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: mktemp: command not found" 1>&2
  exit 1
fi

if which "${bindir}/hack-gcc-specs" 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: ${bindir}/hack-gcc-specs: command not found" 1>&2
  exit 1
fi

if which "${bindir}/g++" 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: ${bindir}/g++: command not found" 1>&2
  exit 1
fi

if which rm 1>/dev/null 2>&1; then
  :
else
  echo "$0: error: rm: command not found" 1>&2
  exit 1
fi

ulimit -t 300
ulimit -m 2097152

specs=`mktemp` || exit

LD_LIBRARY_PATH="$LD_LIBRARY_PATH${LD_LIBRARY_PATH:+:}$libdir"
export LD_LIBRARY_PATH

{ "${bindir}/hack-gcc-specs" > "$specs"; } && "${bindir}/g++" -specs="$specs" "$@" -Wl,-rpath="$libdir"
result=$?

rm -f "$specs"

exit $result
